$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    stagePadding: 0,
    responsive:{
        0:{
            items:1
        },
       740:
       {
            item:3
       },
        990:{
            items:4
        }
        ,
        1200:{
            items:5 
        }
    }
})                      